#
#  Author: Hari Sekhon
#  Date: 2020-03-13 21:10:39 +0000 (Fri, 13 Mar 2020)
#
#  vim:ts=4:sts=4:sw=4:et
#
#  https://github.com/harisekhon/bash-tools
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/harisekhon
#

# BuildKite Pipeline
#
# add this command to the UI and it will read the rest of the steps from here:
#
# - command: buildkite-agent pipeline upload

steps:
  - command: |
        type make 2>/dev/null ||
        if type apk 2>/dev/null; then
            apk add --no-cache --no-progress make
        # apt is /usr/bin/apt
        # Unable to locate an executable at "/Users/hari/.sdkman/candidates/java/current/bin/apt" (-1)
        elif type apt-get 2>/dev/null; then
            apt-get update -q &&
            apt-get install -qy make
        elif type yum 2>/dev/null; then
            rpm -q make || yum install -y make
        elif type brew 2>/dev/null; then
            brew install make
        fi
    label: install make
    timeout: 20  # brew can take 10 mins just to do a brew update
  - wait
  - command: make init
    label: init
    timeout: 2
  - wait
  - command: make ci
    label: build
    timeout: 60
  - wait
  - command: make test
    label: test
    timeout: 120
