#!/usr/bin/env bash
#  vim:ts=4:sts=4:sw=4:et
#
#  Author: Hari Sekhon
#  Date: 2024-10-03 10:41:23 +0300 (Thu, 03 Oct 2024)
#
#  https///github.com/HariSekhon/DevOps-Bash-tools
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

set -euo pipefail
[ -n "${DEBUG:-}" ] && set -x
srcdir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck disable=SC1090,SC1091
. "$srcdir/lib/github.sh"

code="git_commit_times_all_repos.gnuplot"
data="data/git_commit_times_all_repos.dat"
image="images/git_commit_times_all_repos.png"

# shellcheck disable=SC2034,SC2154
usage_description="
Generates a GNUplot graph of Git commit times from all GitHub repos for a given user using the GitHub API

Generates the following files:

    $code - Code

    $data     - Data

    $image     - Image

A MermaidJS version of this program is adjacent in:

    github_graph_commit_times_mermaidjs.sh

A Golang version of this program can be found here:

    https://github.com/HariSekhon/GitHub-Graph-Commit-Times

Fetching GitHub commits via the API is slow so if there is a data cache updated in the last 7 days then uses that
to save time re-fetching the same data. Delete it if you want to refresh

Requires GitHub CLI and GNUplot to be installed and GH_TOKEN to be present
"

# used by usage() in lib/utils.sh
# shellcheck disable=SC2034
usage_args="<username>"

help_usage "$@"

min_args 1 "$@"

username="$1"

for x in $code \
         $data \
         $image; do
    mkdir -p -v "$(dirname "$x")"
done

if file_modified_in_last_days "$data" 7; then
    timestamp "Using cached data: $data"
else
    timestamp "Fetching list of GitHub repos"
    repos="$(get_github_repos "$username")"
    timestamp "Found repos: $(wc -l <<< "$repos" | sed 's/[[:space:]]//g')"
    echo

    while read -r repo; do
        timestamp "Fetching commit times for repo: $repo"
        gh api -H "Accept: application/vnd.github.v3+json" "/repos/$username/$repo/commits" --paginate |
        jq -r '.[].commit.author.date[11:13]'
    done <<< "$repos" |
    sort |
    uniq -c |
    awk '{print $2" "$1}' > "$data"
fi
echo

timestamp "Generating GNUplot code for Commits per Hour"
sed '/^[[:space:]]*$/d' > "$code" <<EOF
#
# Generated by ${0##*/}
#
# from https://github.com/HariSekhon/DevOps-Bash-tools
#
set terminal pngcairo size 1280,720 enhanced font "Arial,14"
set title "Git Commits by Hour"
set xlabel "Hour of Day (UTC)"
set ylabel "Number of Commits"
set grid
#set xtics rotate by -45
set boxwidth 0.8 relative
set style fill solid
set datafile separator " "
# results in X axis labels every 2 years
#set xdata time
#set timefmt "%H"
#set format x "%H"
# trick to get X axis labels for every year
stats "$data" using 1 nooutput
set xrange [STATS_min:STATS_max]
set xtics 1
set output "$image"
plot "$data" using 1:2 with boxes title 'Commits'
EOF
timestamp "Generated GNUplot code: $code"

timestamp "Generating bar chart for Commits per Hour"
gnuplot "$code"
timestamp "Generated bar chart image: $image"
echo

if is_CI; then
    exit 0
fi

timestamp "Opening: $image"
"$srcdir/../media/imageopen.sh" "$image"
