#!/usr/bin/env bash
#  vim:ts=4:sts=4:sw=4:et
#  args: harisekhon
#
#  Author: Hari Sekhon
#  Date: 2020-06-24 17:39:04 +0100 (Wed, 24 Jun 2020)
#
#  https://github.com/HariSekhon/DevOps-Bash-tools
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

set -euo pipefail
[ -n "${DEBUG:-}" ] && set -x
srcdir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck disable=SC1090,SC1091
. "$srcdir/lib/spotify.sh"

# shellcheck disable=SC2034,SC2154
usage_description="
Backs up a given Spotify playlist to text files in both Spotify URI and human readable formats

Spotify track URI format can be copied and pasted back in to Spotify to restore a playlist to a previous state
(for example if you accidentally deleted a track and didn't do an immediate Ctrl-Z / Cmd-Z)

Spotify track URI format can also be combined with spotify_add_to_playlist.sh to restore or add to another playlist

$usage_playlist_help

$usage_auth_help
"

# used by usage() in lib/utils.sh
# shellcheck disable=SC2034
usage_args="<playlist> [<curl_options>]"

help_usage "$@"

min_args 1 "$@"

playlist="$1"
if [ "$playlist" = liked ] || [ "$playlist" = saved ]; then
    playlist="Liked Songs"
fi
liked(){
    [ "$playlist" = "Liked Songs" ]
}

shift || :

spotify_user

if not_blank "${SPOTIFY_BACKUP_DIR:-}"; then
    backup_dir="$SPOTIFY_BACKUP_DIR"
elif [[ "$PWD" =~ playlist ]]; then
    backup_dir="$PWD"
else
    backup_dir="$PWD/playlists"
fi
backup_dir_spotify="$backup_dir/spotify"
if liked; then
    playlist_name="Liked Songs"
fi

mkdir -vp "$backup_dir"
mkdir -vp "$backup_dir_spotify"

if liked; then
    export SPOTIFY_PRIVATE=1
fi
spotify_token

SECONDS=0

playlist_name_to_id(){
    local playlist="$1"
    # generated by spotify_backup_playlists.sh
    local playlists_cache="spotify/playlists.txt"
    if [ -f "$playlists_cache" ]; then
        playlist_id="$(
            awk -v name="$playlist" '
                {
                    id = $1
                    $1 = ""
                    sub(/^[[:space:]]+/, "")
                    if ($0 == name) {
                        print id
                        exit
                    }
                }
            ' "$playlists_cache"
        )"

        if [ -n "$playlist_id" ] && [[ "$playlist_id" =~ ^[A-Za-z0-9]{22}$ ]]; then
            #timestamp "cache hit: $playlist_id"
            echo "$playlist_id"
            return
        fi
    fi
    #timestamp "cache miss: need api lookup"
    SPOTIFY_PLAYLIST_EXACT_MATCH=1 "$srcdir/spotify_playlist_name_to_id.sh" "$playlist"
}
export -f playlist_name_to_id

if liked; then
    echo -n "$playlist_name "

    filename="$("$srcdir/spotify_playlist_to_filename.sh" <<< "$playlist_name")"

    # Caching behaviour
    liked_added_at="$("$srcdir/spotify_api.sh" "/v1/me/tracks?limit=1" | jq -r '.items[0].added_at')"
    liked_timestamp_cache="id/Liked.added_at.txt"
    if [ -f "$liked_timestamp_cache" ] &&
       [ "$liked_added_at" = "$(cat "$liked_timestamp_cache")" ]; then
        echo -n ' => Latest Added Timestamp Unchanged'
    else
        # XXX: sort the Liked URI and track orderings - although this breaks the fidelity between the playlist <=> spotify/playlist formats,
        #      it's necessary to avoid recurring large diffs as Spotify seems to change the output ordering of this
        echo -n "=> URIs "
        #trap_cmd "cd \"$backup_dir_spotify\" && git checkout \"$filename\" &>/dev/null"
        #"$srcdir/spotify_liked_tracks_uri.sh" "$@" | sort -f > "$backup_dir_spotify/$filename"
        #untrap
        # better to just use atomic moves so we can ./commit.sh even while this is running
        # without being prompted with net removals by partially completed downloads
        tmp="$(mktemp)"
        "$srcdir/spotify_liked_tracks_uri.sh" "$@" | sort -f > "$tmp"
        mv -f -- "$tmp" "$backup_dir_spotify/$filename"

        echo -n 'OK => Tracks '
        #trap_cmd "cd \"$backup_dir\" && git checkout \"$filename\" &>/dev/null"
        #"$srcdir/spotify_liked_tracks.sh" "$@" | sort -f > "$backup_dir/$filename"
        tmp="$(mktemp)"
        "$srcdir/spotify_liked_tracks.sh" "$@" | sort -f > "$tmp"
        mv -f -- "$tmp" "$backup_dir/$filename"
        #untrap
        echo "$liked_added_at" > "$liked_timestamp_cache"
        echo -n 'OK'
    fi
else
    playlist_id="$(playlist_name_to_id "$playlist")"
    # not redundant since spotify_backup.sh passes in a playlist ID instead of name for efficiency
    # to avoid lots of name to ID lookups
    playlist_name="$("$srcdir/spotify_playlist_id_to_name.sh" "$playlist_id" "$@")"

    echo -n "$playlist_name "

    filename="$("$srcdir/spotify_playlist_to_filename.sh" <<< "$playlist_name")"

    # XXX: bugfix for 'illegal byte sequence error' for weird unicode chars in the filename
    #filename="$(sed 's/[^[:alnum:][:space:]!"$&'"'"'()+,.\/:<_|–\∕-]/-/g' <<< "$filename")"
    #echo "Saving to filename: $filename"

    #playlist_json="$("$srcdir/spotify_playlist_json.sh" "$playlist_id")"
    # optimization to pull only the fields we need without the first 100 tracks
    playlist_json="$("$srcdir/spotify_api.sh" "/v1/playlists/$playlist_id?fields=snapshot_id,description")"
    #if [ -n "${SPOTIFY_DUMP_HEADERS:-}" ]; then
    #    "$srcdir/../bin/curl_auth.sh" -i "$url_base/$url_path" "$@" | sed '/^[[:space:]]*$/,$d' >&2
    #    exit 1
    #fi

    echo -n "=> Description "
    description_file="$backup_dir/$filename.description"
    # playlist descriptions are HTML encoded
    jq -r '.description' <<< "$playlist_json" | tr -d '\n' | sed 's/\&amp;/\&/g' > "$description_file"
    if [ -f "$description_file" ]; then
        # if file is blank then no description is set, remove the useless file
        if ! [ -s "$description_file" ]; then
            rm -f -- "$description_file"
            echo -n "None"
        else
            echo -n "OK"
        fi
    fi

    mkdir -p "$backup_dir/id"
    id_file="$backup_dir/id/$filename.id.txt"
    snapshot_id="$(jq -r '.snapshot_id' <<< "$playlist_json" | tr -d '\n')"

    # renaming a playlist or changing its description also changes the snapshot ID,
    # not just adding/removing/reordering tracks, triggering a full re-download
    if [ -f "$id_file" ] && [ "$snapshot_id" = "$(cat "$id_file")" ]; then
        echo -n ' => Snapshot ID unchanged'
    else
        # reset to the last good version to avoid having partial files which will offer bad commits of removed tracks
        echo -n " => URIs "
        #trap_cmd "cd \"$backup_dir_spotify\" && git checkout \"$filename\" &>/dev/null"
        #"$srcdir/spotify_playlist_tracks_uri.sh" "$playlist_id" "$@" > "$backup_dir_spotify/$filename"
        tmp="$(mktemp)"
        "$srcdir/spotify_playlist_tracks_uri.sh" "$playlist_id" "$@" > "$tmp"
        mv -f "$tmp" "$backup_dir_spotify/$filename"
        #untrap
        # try to avoid hitting HTTP 429 rate limiting
        #sleep 0.1
        num_track_uris="$(wc -l < "$backup_dir_spotify/$filename" | sed 's/[[:space:]]*//')"

        echo -n "OK ($num_track_uris) => Tracks "
        # reset to the last good version to avoid having partial files which will offer bad commits of removed tracks
        #trap_cmd "cd \"$backup_dir\" && git checkout \"$filename\" &>/dev/null"
        #"$srcdir/spotify_playlist_tracks.sh" "$playlist_id" "$@" > "$backup_dir/$filename"
        #untrap
        # better to just use atomic moves so we can ./commit.sh even while this is running
        # without being prompted with net removals by partially completed downloads
        tmp="$(mktemp)"
        "$srcdir/spotify_playlist_tracks.sh" "$playlist_id" "$@" > "$tmp"
        mv -f "$tmp" "$backup_dir/$filename"
        echo "$snapshot_id" > "$id_file"
        echo -n 'OK'
    fi
fi
echo " => $SECONDS secs"

# try to avoid hitting HTTP 429 rate limiting
#sleep 0.1
