#
#  Author: Hari Sekhon
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/bash-tools
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/HariSekhon
#

---
name: Mac 10.15

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 7 * * *'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event.repository.fork == false
    name: Mac 10.15
    uses: HariSekhon/GitHub-Actions/.github/workflows/mac.yaml@master
    with:
      version: 10.15
      debug: ${{ github.event.inputs.debug || false }}
